package com.vuclip.ubs.subscription_service;

public enum StatusSummary {
	ACTIVATION_IN_PROGRESS, ACTIVE, ACTIVE_NO_VALIDITY, INACTIVE, INACTIVE_WITH_VALIDITY, DEACTIVATION_IN_PROGRESS, BLACK_LISTED,NOT_BLACKLISTED, COOL_DOWNED;
}
